version: '3.8'

services:
  app:
    build:
      context: ./app
    networks:
      - app-network
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
    networks:
      - app-network
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
